import sys, os, argparse
from glob import glob
from time import perf_counter
from collections import defaultdict

if __name__ == "__main__":
    print("AssimpUnityBuild.py: started")

    parser = argparse.ArgumentParser(description="SpaRcle Code generator")
    parser.add_argument("--sources", required=True)
    parser.add_argument("--out", required=True, help="Output directory for the generated files")
    args = parser.parse_args()

    if not os.path.exists(args.out):
        os.makedirs(args.out)

    files = str(args.sources).split(';')

    # Создаём группы по последней папке
    groups = defaultdict(list)

    group_key = "root"

    non_merge_files = [
        "FindDegenerates", "FBXConverter", "BlenderScene", "IOSystem", "DefaultIOSystem", "Importer", "Exporter"
    ]

    merge_folders = [
        ['merged1', ['CSM', 'clipper', 'MDC', 'OFF', 'MDL', 'MD2', 'MD3', 'MD5', 'MMD', 'NDO', 'Q3D', 'Raw', 'Q3BSP', 'glTF2']],
        ['merged2', ['SIB', 'SMD', 'Step', 'STEPParser', 'STL', 'ASE', 'AMF', '3DS', '3MF', 'AC', 'Assbin']],
        ['merged3', ['OpenGEX', 'Terragen', 'Ogre', 'M3D', 'HalfLife', 'Irr', 'NFF', 'Obj', 'Pbrt', 'HMPLoader']],
        ['merged4', ['IFC', 'LWS', 'LWO', 'Ply', 'HMP', 'COB', 'CApi', 'BVH', 'B3D']],
        ['merged5', ['IQM', 'MS3D', 'Assxml', 'Unreal', 'XGL', 'X', 'code']],
        ['merged6', ['glTF', 'Collada', 'Assjson', 'Open3DGC', 'DXF']],
    ]

    used_files = set()

    for file_path in files:
        if file_path.endswith(".h") or file_path.endswith(".hpp") or file_path.endswith(".inl"):
            continue
        norm_path = file_path.replace('\\', '/')
        dir_parts = norm_path.split('/')

        if len(dir_parts) >= 2:
            group_key = dir_parts[-2]  # последняя папка
        else:
            group_key = "root"

        ext = file_path.split('.')[-1]

        # get between last slash and first dot
        file_name = file_path.split('/')[-1].split('.')[0]
        if file_name in non_merge_files:
            group_key = file_name
        else:
            for merge_folder, sub_folders in merge_folders:
                if group_key in sub_folders:
                    group_key = merge_folder
                    break

        groups[group_key + '-' + ext].append(file_path)

    for group, group_files in groups.items():
        extension = group_files[0].split('.')[-1]
        group_file_path = f"{args.out}/{group}.assimp-codegen.{extension}"
        file_name = group_file_path.split('/')[-1]

        cpp_files = []

        for file_path in group_files:
            cpp_files.append(file_path)

        if len(cpp_files) == 0:
            continue

        file_text = f"// This file is generated by AssimpUnityBuild.py\n\n"
        for file_path in cpp_files:
            file_text += f'#include "{file_path}"\n'

        old_text = ""
        if os.path.isfile(group_file_path):
            with open(group_file_path, "r") as file:
                old_text = file.read()

            if old_text == file_text:
                print(f"AssimpUnityBuild.py: file '{file_name}' is already up to date, skipping")
                used_files.add(file_name)
                continue

        with open(group_file_path, "w") as file:
            print(f"AssimpUnityBuild.py: creating cxx file for group '{group}' at '{group_file_path}'")
            used_files.add(file_name)
            file.write(file_text)

    for file in glob(f"{args.out}/*.assimp-codegen.*"):
        if os.path.isfile(file):
            file_name = file.replace('\\', '/').split('/')[-1]
            if file_name in used_files:
                continue
            print(f"AssimpUnityBuild.py: removing file '{file_name}', because it was not used in any group")
            os.remove(file)

    print("AssimpUnityBuild.py: finished")