import json
import fnmatch
import os
import argparse
from pathlib import Path
from glob import glob
from time import perf_counter


def chunk_list(lst, chunk_size=30):
    return [lst[i : i + chunk_size] for i in range(0, len(lst), chunk_size)]


def write_if_changed(path: Path, content: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            old = f.read()
        if old == content:
            print(f"BuildGenerator.py: no changes in {path}, skipping write.")
            return False  # не изменили
    except FileNotFoundError:
        pass

    with open(path, "w", encoding="utf-8") as f:
        print(f"BuildGenerator.py: file {path} outdated or missing, writing new content.")
        f.write(content)
    return True  # изменили


def generate_unity_build(module_name: str, out_dir: Path, cxx_files: list, cpp_files: list):
    result = ""

    for cxx_file in cxx_files:
        result += f"{cxx_file}\n"

    unity_sources_path = out_dir / "unity"
    unity_sources_path.mkdir(parents=True, exist_ok=True)

    cpp_chunks = chunk_list(cpp_files, 30)

    for i, chunk in enumerate(cpp_chunks):
        unity_path = unity_sources_path / f"srinc_{i}.cxx"

        content = (
            "// This file is generated by SpaRcle Studio code-generator ^_^\n\n"
            f"#include <{module_name}/stdInclude.h>\n\n"
        )
        for file in chunk:
            content += f'#include "{file}"\n'

        write_if_changed(unity_path, content)
        result += f"{normalize_path(unity_sources_path.joinpath(f"srinc_{i}.cxx"))}\n"

    write_if_changed(out_dir / "main.srinc", result)


def generate_incremental_build(out_dir: Path, cxx_files: list, cpp_files: list):
    files = cxx_files + cpp_files

    result = ""
    for file in files:
        result += f"{file}\n"

    write_if_changed(out_dir / "main.srinc", result)


def gather_cxx_files(project_root: Path) -> list[str]:
    result = []

    result += glob(str(project_root / "*.cxx"))
    result += [str(p) for p in (project_root / "cxx").rglob("*.cxx")]

    return [str(Path(p).as_posix()) for p in result]


def normalize_path(path):
    """Нормализует слеши в путях для различных ОС."""
    return os.path.normpath(path).replace('\\', '/')


def gather_cpp_files(src_dir: Path, config):
    includes = config.get('include', [])
    excludes = config.get('exclude', [])

    includes = [normalize_path(p) for p in includes]
    excludes = [normalize_path(p) for p in excludes]

    collected_files = []

    try:
        for dir_path, _, _ in os.walk(src_dir):
            for file_path in glob(os.path.join(dir_path, '*.*'), recursive=False):
                file_path = normalize_path(file_path)
                if any((check_dir in file_path) for check_dir in excludes):
                    continue
                if any((check_dir in file_path) for check_dir in includes):
                    collected_files.append(file_path)

    except Exception as e:
        print(f'Error during file collection: {e}')

    return collected_files


if __name__ == "__main__":
    print("BuildGenerator.py: started")
    timer_start = perf_counter()

    parser = argparse.ArgumentParser(description="SpaRcle Code generator")
    parser.add_argument("--project-path", required=True, help="Path to the project.")
    parser.add_argument(
        "--out", required=True, help="Output directory for the generated files"
    )
    parser.add_argument(
        "--unity",
        required=True,
        choices=["ON", "OFF"],
        help="Generate Unity build files.",
    )

    args = parser.parse_args()

    project_path = Path(args.project_path)
    config_file = project_path.joinpath("srinc.json")

    config = json.load(open(config_file, "r"))
    out_directory = Path(args.out).joinpath(config["module_name"])

    print(
        f"BuildGenerator.py: generating build files for project at:\n\t\t{project_path}"
    )
    print(f"BuildGenerator.py: output directory is:\n\t\t{out_directory}")
    print(f"BuildGenerator.py: unity build is {args.unity}")

    if not os.path.exists(out_directory):
        os.makedirs(out_directory)

    cxx_files = gather_cxx_files(project_path)
    cpp_files = gather_cpp_files(project_path.joinpath("src/"), config)

    if args.unity == "ON":
        generate_unity_build(config["module_name"], out_directory, cxx_files, cpp_files)
    else:
        generate_incremental_build(out_directory, cxx_files, cpp_files)

    timer_stop = perf_counter()

    print(
        "BuildGenerator.py: finished. Elapsed time: ",
        timer_stop - timer_start,
        " seconds",
    )
