set(ASSIMP_NO_EXPORT OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_BUILD_TESTS OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_INSTALL OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_BUILD_ASSIMP_VIEW OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE INTERNAL "" FORCE)
set(ASSIMP_BUILD_MINIZIP ON CACHE INTERNAL "" FORCE)

set(SR_COMMON_ASSIMP_UNITY_BUILD_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/py/AssimpUnityBuild.py")
set(SR_COMMON_ASSIMP_UNITY_BUILD_OUT_FOLDER "${CMAKE_CURRENT_BINARY_DIR}/AssimpUnityBuild")

function(SR_COMMON_ASSIMP_SOURCES_MODIFY_HOOK value)
    execute_process(
        COMMAND ${SR_PYTHON_EXECUTABLE} ${SR_COMMON_ASSIMP_UNITY_BUILD_SCRIPT}
        --sources "${value}"
        --out "${SR_COMMON_ASSIMP_UNITY_BUILD_OUT_FOLDER}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error_output
    )

    file(GLOB cxx_files "${SR_COMMON_ASSIMP_UNITY_BUILD_OUT_FOLDER}/*.assimp-codegen.*")
    set(assimp_src_updated ${cxx_files} CACHE INTERNAL "" FORCE )

    if (result EQUAL "0")
        message(STATUS "Assimp sources modified successfully:\n${output}")
    else()
        message(FATAL_ERROR "Assimp sources modification failed with error:\n${error_output}")
    endif()
endfunction()

set(ASSIMP_SOURCES_MODIFY_HOOK SR_COMMON_ASSIMP_SOURCES_MODIFY_HOOK)

set(SR_ASSIMP_DISABLED_IMPORTERS
    ASSIMP_BUILD_NO_AC_IMPORTER
    ASSIMP_BUILD_NO_AMF_IMPORTER
    ASSIMP_BUILD_NO_ASE_IMPORTER
    ASSIMP_BUILD_NO_B3D_IMPORTER
    ASSIMP_BUILD_NO_ASSBIN_IMPORTER
    ASSIMP_BUILD_NO_COB_IMPORTER
    ASSIMP_BUILD_NO_COLLADA_IMPORTER
    ASSIMP_BUILD_NO_CSM_IMPORTER
    ASSIMP_BUILD_NO_3MF_IMPORTER
    ASSIMP_BUILD_NO_DXF_IMPORTER
    ASSIMP_BUILD_NO_GLTF_EXPORTER
    ASSIMP_BUILD_NO_HMP_IMPORTER
    ASSIMP_BUILD_NO_IFC_IMPORTER
    ASSIMP_BUILD_NO_IRR_IMPORTER
    ASSIMP_BUILD_NO_LWO_IMPORTER
    ASSIMP_BUILD_NO_MD2_IMPORTER
    ASSIMP_BUILD_NO_MD3_IMPORTER
    ASSIMP_BUILD_NO_MD5_IMPORTER
    ASSIMP_BUILD_NO_MDC_IMPORTER
    ASSIMP_BUILD_NO_MDL_IMPORTER
    ASSIMP_BUILD_NO_MMD_IMPORTER
    ASSIMP_BUILD_NO_MS3D_IMPORTER
    ASSIMP_BUILD_NO_NDO_IMPORTER
    ASSIMP_BUILD_NO_NFF_IMPORTER
    ASSIMP_BUILD_NO_OGRE_IMPORTER
    ASSIMP_BUILD_NO_OPENGEX_EXPORTER
    ASSIMP_BUILD_NO_OPENGEX_IMPORTER
    ASSIMP_BUILD_NO_PLY_IMPORTER
    ASSIMP_BUILD_NO_Q3BSP_IMPORTER
    ASSIMP_BUILD_NO_Q3D_IMPORTER
    ASSIMP_BUILD_NO_RAW_IMPORTER
    ASSIMP_BUILD_NO_SMD_IMPORTER
    ASSIMP_BUILD_NO_STL_IMPORTER
    ASSIMP_BUILD_NO_X3D_IMPORTER
    ASSIMP_BUILD_NO_X_IMPORTER
    ASSIMP_BUILD_NO_XGL_IMPORTER
    ASSIMP_BUILD_NO_M3D_IMPORTER
    ASSIMP_BUILD_NO_IRRMESH_IMPORTER
    ASSIMP_BUILD_NO_LWS_IMPORTER
    ASSIMP_BUILD_NO_OFF_IMPORTER
    ASSIMP_BUILD_NO_SIB_IMPORTER
    ASSIMP_BUILD_NO_TERRAGEN_IMPORTER
    ASSIMP_BUILD_NO_3D_IMPORTER
)